"""Claude API: generate teacher and parent summaries from a lesson transcript."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field

import anthropic

logger = logging.getLogger(__name__)


@dataclass
class NarrativeResult:
    teacher_summary: str = ""
    teacher_summary_formal: str | None = None
    parent_summary: str = ""
    suggested_assignments: list[dict[str, str]] = field(default_factory=list)
    pieces_detected: list[str] = field(default_factory=list)
    lesson_segments: list[dict] | None = None


SYSTEM_PROMPT = """\
You are a music lesson documentation assistant for Orpheus.
You receive a unified timeline from a music lesson and generate summaries.

TIMELINE FORMAT: The timeline interleaves three types of entries:
- SPEECH: Teacher or student speech transcribed from audio. \
May contain speech-to-text errors (see cleaning rules below).
- MUSIC-N: A numbered music segment where the student or teacher played. \
Includes duration, energy level (quiet/moderate/loud), energy profile \
(steady/moderate/varied), and cross-similarity scores to other music segments.
- SILENCE: A gap of 3+ seconds with no speech or playing.

Use MUSIC segments and their features to understand what happened between \
speech. High cross-similarity (>0.85) between two music segments means they \
are likely the same passage being repeated (drill/practice attempts). Energy \
and duration help distinguish run-throughs from short focused attempts.

TRANSCRIPT CLEANING: The speech was generated by speech-to-text and may \
contain errors, especially with musical terminology. Before generating \
summaries, mentally correct likely errors such as:
- Misspelled composer names (e.g., "the voldi" → "Vivaldi", "bark" → "Bach", \
"more zart" → "Mozart")
- Garbled musical terms (e.g., "speak auto" → "spiccato", "the tosh" → \
"détaché", "pizz a cato" → "pizzicato")
- "bar" and "measure" mean the same thing
- Number-like sounds near musical context are likely measure numbers or tempo \
markings
Use your musical knowledge to infer what was actually said. Generate summaries \
using the corrected terms, not the raw transcription errors.

*** CRITICAL OUTPUT RULE — READ THIS FIRST ***
The MUSIC-N labels (e.g. MUSIC-1, MUSIC-13), similarity scores (e.g. 0.98), \
energy levels, energy profiles, and all audio feature data are INTERNAL \
metadata for clip creation ONLY. They must NEVER appear in teacher_summary, \
parent_summary, teacher_summary_formal, or any prose text. \
If you find yourself writing "MUSIC-" or a similarity score in a summary, \
STOP and rephrase using natural musical language instead \
(e.g. "consistent repetition of the passage" not \
"high similarity between MUSIC-13 and MUSIC-23 (0.98)"). \
Violating this rule makes the output unusable.
*** END CRITICAL OUTPUT RULE ***

Use the timestamps to understand lesson structure and pacing — how long was \
spent on each piece or activity. You don't need to include timestamps in the \
summaries.

If a previous lesson summary is provided, use it for context. Note any \
continuity — whether assigned pieces were revisited, whether previously noted \
areas received attention. Don't force comparisons if the current lesson covers \
entirely different material. If no previous lesson is provided, this is a new \
student — skip any references to prior lessons.

TEACHER SUMMARY: Concise, specific, uses musical terminology where present in
the transcript. Focus on what was covered, measurable progress, and areas
needing attention.

FORMATTING — this will be read on a phone screen between lessons, so it must \
be scannable in 10 seconds:
- Write multiple SHORT paragraphs (2-4 sentences each), separated by blank \
lines (\\n\\n). Never write one long wall of text.
- Use bullet points when listing technical observations or specific areas \
worked on — but keep it natural, not every paragraph needs bullets.
- Suggest 2-3 specific practice assignments based on what the teacher discussed.

PARENT SUMMARY: Write this as the teacher speaking directly to the parent about
their child. Use the student's name in third person ("Sofia had a great lesson
today" NOT "Great job, Sofia!"). The tone should be warm, encouraging, and
professional — like a teacher's note sent home.

FORMATTING — parents read this on their phone, so break it into 2-3 short \
warm paragraphs separated by blank lines (\\n\\n). You may use a short bullet \
list for practice suggestions if it helps readability. Never write one long \
dense paragraph.

Structure:
1. Open with something genuinely positive about today's lesson
2. Briefly describe what was worked on (in non-technical language)
3. Give one or two specific things the parent can encourage at home
4. End with recommended daily practice duration

NEVER address the student directly — this message goes to the parent.
NEVER use these words in the parent summary: struggled, failed, couldn't, wrong,
mistake, problem, weak, poor, bad, behind.

PIECES DETECTED: List ONLY pieces the student actually PLAYED or PRACTICED \
during this lesson. Do NOT include pieces mentioned merely as references, \
comparisons, or examples (e.g., if the teacher says "this passage is similar \
to the Chopin Etude", do not list the Chopin Etude unless the student played it).

Use short, clean piece names as a musician would say them — e.g., \
"Vivaldi Concerto in A minor", "Courante", "A minor scale", \
"Kreutzer Etude No. 8". Never add parenthetical descriptions or analysis \
to piece names (no "Bach piece (with inversion and deceptive cadence)", \
no "Clavichord piece (unspecified)"). If the exact piece cannot be identified, \
use the most specific short name possible (e.g., "Clavichord piece" not \
"Clavichord piece (unspecified)"). Scales and exercises count as pieces. \
Do not list the same piece twice with different descriptions.

LESSON SEGMENTS (TOPIC BOUNDARIES): Divide the lesson into topic segments. \
The full audio will be sliced at these boundaries so every second of the \
lesson is preserved and accessible as a topic clip.

Each segment represents a natural topic section (e.g., "Scale warm-up", \
"Vivaldi — string crossings drill", "Sight-reading new piece"). Each segment \
has start_seconds, end_seconds, label, and type.

CRITICAL: Segments MUST cover the entire lesson from start to finish with \
no gaps and no overlaps. The first segment starts at 0.0 and the last \
segment ends at the lesson duration. Aim for 2-8 segments.

Segment types: "warmup", "run_through", "focused_practice", "sight_reading", \
"technique_work", "review", "other".

Segment labels should be short, descriptive, and context-aware. Include what \
was practiced and the type of work. \
Good: "E major scale — position shift practice" \
Good: "Vivaldi mm. 1-44 — run-through" \
Good: "String crossing passage — slow practice drill" \
Bad: "E major scale — position shift practice (4 attempts)" \
Bad: "Attempt 1" \
Bad: "Scale"

Respond in JSON format ONLY (no markdown fences):
{
    "teacher_summary": "...",
    "parent_summary": "...",
    "pieces_detected": ["..."],
    "suggested_assignments": [
        {"description": "...", "details": "..."}
    ],
    "lesson_segments": [
        {
            "start_seconds": 0.0,
            "end_seconds": 90.0,
            "label": "A minor scale warm-up",
            "type": "warmup"
        },
        {
            "start_seconds": 90.0,
            "end_seconds": 460.0,
            "label": "Vivaldi — string crossings drill",
            "type": "focused_practice"
        }
    ]
}
"""

FORMAL_ADDENDUM = """
Additionally, generate a formal documentation-style record suitable for
professional or legal purposes. Use clinical, precise language. Structure as:
- Date, time, duration header
- Numbered list of content covered
- Observations section with objective technical notes
- Assignments given with specific targets

Add a "teacher_summary_formal" field to the JSON response.
"""


def generate_summaries(
    transcript: str,
    student_name: str,
    instrument: str = "violin",
    duration_seconds: int | None = None,
    summary_style: str = "standard",
    previous_lesson_context: str | None = None,
    api_key: str | None = None,
) -> NarrativeResult:
    """Send the lesson transcript to Claude and parse the structured response.

    Parameters
    ----------
    transcript:
        Full text transcript of the lesson.
    student_name:
        Name of the student.
    instrument:
        Instrument being studied.
    duration_seconds:
        Lesson duration in seconds, if known.
    summary_style:
        "standard" or "formal".
    previous_lesson_context:
        Formatted summary + assignments from the student's most recent
        completed lesson, or *None* if this is their first lesson.
    api_key:
        Anthropic API key. If *None*, the client reads ANTHROPIC_API_KEY env var.
    """
    if not transcript.strip():
        logger.warning("Empty transcript — returning placeholder summaries")
        return NarrativeResult(
            teacher_summary="No speech was detected in this lesson recording.",
            parent_summary=(
                f"{student_name} had a lesson today. "
                "Ask your teacher for details about what was covered."
            ),
        )

    system = SYSTEM_PROMPT
    if summary_style == "formal":
        system += FORMAL_ADDENDUM

    duration_str = ""
    if duration_seconds and duration_seconds > 0:
        if duration_seconds >= 60:
            mins = duration_seconds // 60
            duration_str = f"\nLesson duration: {mins} minutes"
        else:
            duration_str = f"\nLesson duration: {duration_seconds} seconds"

    prev_context_block = ""
    if previous_lesson_context:
        prev_context_block = f"\n{previous_lesson_context}\n"

    user_message = (
        f"Student: {student_name}\n"
        f"Instrument: {instrument}{duration_str}\n"
        f"{prev_context_block}\n"
        f"Timestamped lesson transcript:\n{transcript}"
    )

    client = anthropic.Anthropic(api_key=api_key) if api_key else anthropic.Anthropic()

    logger.info("Sending transcript (%d chars) to Claude for narrative generation", len(transcript))

    message = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=4096,
        system=system,
        messages=[{"role": "user", "content": user_message}],
    )

    raw = message.content[0].text
    logger.info("Received narrative response (%d chars)", len(raw))

    data = _parse_json_response(raw)
    if data is None:
        logger.error("Failed to parse Claude response as JSON: %s", raw[:300])
        return NarrativeResult(
            teacher_summary=raw,
            parent_summary=raw,
        )

    lesson_segments = _validate_lesson_segments(data.get("lesson_segments"))

    return NarrativeResult(
        teacher_summary=data.get("teacher_summary", ""),
        teacher_summary_formal=data.get("teacher_summary_formal"),
        parent_summary=data.get("parent_summary", ""),
        suggested_assignments=data.get("suggested_assignments", []),
        pieces_detected=data.get("pieces_detected", []),
        lesson_segments=lesson_segments,
    )


_VALID_SEGMENT_TYPES = {
    "warmup", "run_through", "focused_practice", "sight_reading",
    "technique_work", "review", "other",
}


def _validate_lesson_segments(raw_segments: object) -> list[dict] | None:
    """Validate and normalize lesson_segments from the LLM response.

    Handles both flat segments (legacy) and hierarchical segments with
    nested clips.  Returns a list of validated segment dicts, or None
    if the data is missing or malformed.  Never raises — always degrades
    gracefully.
    """
    if not isinstance(raw_segments, list) or len(raw_segments) == 0:
        return None

    validated: list[dict] = []
    for seg in raw_segments:
        if not isinstance(seg, dict):
            logger.warning("Narrative: skipping non-dict lesson segment: %s", seg)
            continue
        try:
            start = float(seg["start_seconds"])
            end = float(seg["end_seconds"])
            label = str(seg.get("label", "")).strip()
        except (KeyError, TypeError, ValueError) as exc:
            logger.warning("Narrative: skipping malformed lesson segment %s: %s", seg, exc)
            continue

        if end <= start or not label:
            logger.warning("Narrative: skipping invalid segment (start=%.1f end=%.1f label=%r)", start, end, label)
            continue

        segment: dict = {
            "start_seconds": round(start, 3),
            "end_seconds": round(end, 3),
            "label": label,
        }

        # Segment type
        seg_type = str(seg.get("type", "other")).strip()
        if seg_type in _VALID_SEGMENT_TYPES:
            segment["type"] = seg_type

        validated.append(segment)

    return validated if validated else None


def _parse_json_response(raw: str) -> dict | None:
    """Parse a JSON response that may be wrapped in markdown code fences.

    Handles these formats:
      - Plain JSON: {"teacher_summary": "..."}
      - Fenced:     ```json\n{"teacher_summary": "..."}\n```
      - Fenced:     ```\n{"teacher_summary": "..."}\n```
    """
    import re

    text = raw.strip()

    # Strip markdown code fences if present
    fence_match = re.match(r"^```(?:json)?\s*\n?(.*?)\n?\s*```$", text, re.DOTALL)
    if fence_match:
        text = fence_match.group(1).strip()

    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass

    # Last resort: find the first { ... } block in the response
    brace_match = re.search(r"\{.*\}", text, re.DOTALL)
    if brace_match:
        try:
            parsed = json.loads(brace_match.group(0))
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            pass

    return None
