"""Claude API: generate teacher and parent summaries from a lesson transcript."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field

import anthropic

logger = logging.getLogger(__name__)


@dataclass
class NarrativeResult:
    teacher_summary: str = ""
    teacher_summary_formal: str | None = None
    parent_summary: str = ""
    suggested_assignments: list[dict[str, str]] = field(default_factory=list)
    pieces_detected: list[str] = field(default_factory=list)


SYSTEM_PROMPT = """\
You are a music lesson documentation assistant for Orpheus.
You receive a transcript from a music lesson and generate summaries.

TRANSCRIPT CLEANING: The transcript was generated by speech-to-text and may \
contain errors, especially with musical terminology. Before generating \
summaries, mentally correct likely errors such as:
- Misspelled composer names (e.g., "the voldi" → "Vivaldi", "bark" → "Bach", \
"more zart" → "Mozart")
- Garbled musical terms (e.g., "speak auto" → "spiccato", "the tosh" → \
"détaché", "pizz a cato" → "pizzicato")
- "bar" and "measure" mean the same thing
- Number-like sounds near musical context are likely measure numbers or tempo \
markings
Use your musical knowledge to infer what was actually said. Generate summaries \
using the corrected terms, not the raw transcription errors.

The transcript includes timestamps. Use these to understand lesson structure \
and pacing, such as how long was spent on each piece or activity. You don't \
need to include timestamps in the summaries.

TEACHER SUMMARY: Concise, specific, uses musical terminology where present in
the transcript. Focus on what was covered, measurable progress, and areas
needing attention. Suggest 2-3 specific practice assignments based on what the
teacher discussed.

PARENT SUMMARY: Write this as the teacher speaking directly to the parent about
their child. Use the student's name in third person ("Sofia had a great lesson
today" NOT "Great job, Sofia!"). The tone should be warm, encouraging, and
professional — like a teacher's note sent home. Structure:
1. Open with something genuinely positive about today's lesson
2. Briefly describe what was worked on (in non-technical language)
3. Give one or two specific things the parent can encourage at home
4. End with recommended daily practice duration

NEVER address the student directly — this message goes to the parent.
NEVER use these words in the parent summary: struggled, failed, couldn't, wrong,
mistake, problem, weak, poor, bad, behind.

PIECES DETECTED: Extract any piece or song names mentioned in the transcript.

Respond in JSON format ONLY (no markdown fences):
{
    "teacher_summary": "...",
    "parent_summary": "...",
    "pieces_detected": ["..."],
    "suggested_assignments": [
        {"description": "...", "details": "..."}
    ]
}
"""

FORMAL_ADDENDUM = """
Additionally, generate a formal documentation-style record suitable for
professional or legal purposes. Use clinical, precise language. Structure as:
- Date, time, duration header
- Numbered list of content covered
- Observations section with objective technical notes
- Assignments given with specific targets

Add a "teacher_summary_formal" field to the JSON response.
"""


def generate_summaries(
    transcript: str,
    student_name: str,
    instrument: str = "violin",
    duration_seconds: int | None = None,
    summary_style: str = "standard",
    api_key: str | None = None,
) -> NarrativeResult:
    """Send the lesson transcript to Claude and parse the structured response.

    Parameters
    ----------
    transcript:
        Full text transcript of the lesson.
    student_name:
        Name of the student.
    instrument:
        Instrument being studied.
    duration_seconds:
        Lesson duration in seconds, if known.
    summary_style:
        "standard" or "formal".
    api_key:
        Anthropic API key. If *None*, the client reads ANTHROPIC_API_KEY env var.
    """
    if not transcript.strip():
        logger.warning("Empty transcript — returning placeholder summaries")
        return NarrativeResult(
            teacher_summary="No speech was detected in this lesson recording.",
            parent_summary=(
                f"{student_name} had a lesson today. "
                "Ask your teacher for details about what was covered."
            ),
        )

    system = SYSTEM_PROMPT
    if summary_style == "formal":
        system += FORMAL_ADDENDUM

    duration_str = ""
    if duration_seconds:
        mins = duration_seconds // 60
        duration_str = f"\nLesson duration: {mins} minutes"

    user_message = (
        f"Student: {student_name}\n"
        f"Instrument: {instrument}{duration_str}\n\n"
        f"Timestamped lesson transcript:\n{transcript}"
    )

    client = anthropic.Anthropic(api_key=api_key) if api_key else anthropic.Anthropic()

    logger.info("Sending transcript (%d chars) to Claude for narrative generation", len(transcript))

    message = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=2000,
        system=system,
        messages=[{"role": "user", "content": user_message}],
    )

    raw = message.content[0].text
    logger.info("Received narrative response (%d chars)", len(raw))

    data = _parse_json_response(raw)
    if data is None:
        logger.error("Failed to parse Claude response as JSON: %s", raw[:300])
        return NarrativeResult(
            teacher_summary=raw,
            parent_summary=raw,
        )

    return NarrativeResult(
        teacher_summary=data.get("teacher_summary", ""),
        teacher_summary_formal=data.get("teacher_summary_formal"),
        parent_summary=data.get("parent_summary", ""),
        suggested_assignments=data.get("suggested_assignments", []),
        pieces_detected=data.get("pieces_detected", []),
    )


def _parse_json_response(raw: str) -> dict | None:
    """Parse a JSON response that may be wrapped in markdown code fences.

    Handles these formats:
      - Plain JSON: {"teacher_summary": "..."}
      - Fenced:     ```json\n{"teacher_summary": "..."}\n```
      - Fenced:     ```\n{"teacher_summary": "..."}\n```
    """
    import re

    text = raw.strip()

    # Strip markdown code fences if present
    fence_match = re.match(r"^```(?:json)?\s*\n?(.*?)\n?\s*```$", text, re.DOTALL)
    if fence_match:
        text = fence_match.group(1).strip()

    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass

    # Last resort: find the first { ... } block in the response
    brace_match = re.search(r"\{.*\}", text, re.DOTALL)
    if brace_match:
        try:
            parsed = json.loads(brace_match.group(0))
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            pass

    return None
